name: Android CI Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Setup Gradle Wrapper
      run: |
        gradle wrapper --gradle-version 8.5
        chmod +x gradlew

    # הפקודה הזו תדפיס ללוג כל דבר שקורה בבנייה כולל שגיאות נסתרות
    - name: Build Debug APK
      run: ./gradlew clean assembleDebug --no-daemon --info --stacktrace

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: screentool-apk
        path
